cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

listings/urls.py
from django.urls import path 

from . import views

app_name = 'listings'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>', views.product_list, name='product_list_by_category'),
    path('<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),

]

orders/urls.py
from django.urls import path
from . import views

from django.contrib.admin.views.decorators import staff_member_required
from solarlynx.decorators import user_created_order

app_name='orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/pdf/', staff_member_required(views.invoice_pdf), name='invoice_pdf'),
    path('order/<int:order_id>/', user_created_order(views.order_detail), name='order_detail'),
    path('order/<int:order_id>/pdf/', user_created_order(views.invoice_pdf), name='customer_invoice_pdf'),

]

solarlynx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('listings.urls')),
 

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.forms import NumberInput 

class CartAddProductForm(forms.Form):

    quantity = forms.IntegerField(
        min_value = 1,
        widget = NumberInput(attrs={'class': 'form-control text-center px-3',
        'value': 1
        })
    )

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from listings.models import Product 
from .forms import CartAddProductForm
from decimal import Decimal


# Create your views here.
def get_cart(request):
    cart = request.session.get(settings.CART_ID)
    if not cart:
        cart = request.session[settings.CART_ID]={}
    return cart

def cart_add(request, product_id):
    cart = get_cart(request)
    print(cart)
    product = get_object_or_404(Product, id=product_id)
    product_id = str(product.id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data

        if product_id not in cart:

            cart[product_id] = {
                'quantity':0,
                'price':str(product.price)
            }
        if request.POST.get('overwrite_qty'):

            cart[product_id]['quantity'] = cd['quantity']
        else:
            cart[product_id]['quantity'] += cd['quantity']

        request.session.modified = True
        return redirect('cart:cart_detail')




def cart_detail(request):

    cart = get_cart(request)
    product_ids = cart.keys()
    products = Product.objects.filter(id__in=product_ids)
    temp_cart = cart.copy()

    for product in products:
        cart_item = temp_cart[str(product.id)]
        cart_item['product']=product
        cart_item['total_price'] = (Decimal(cart_item['price']) * cart_item['quantity'])

        cart_item['update_quantity_form'] = CartAddProductForm(initial={'quantity': cart_item['quantity']}) 

    cart_total_price = sum(Decimal(item['price']) * item['quantity'] for item in temp_cart.values())
    return render(request, 'cart/detail.html',{'cart':temp_cart.values(), 'cart_total_price': cart_total_price})

def cart_remove(request, product_id):

    cart = get_cart(request)
    product_id = str(product_id)
    if product_id in cart:
        del cart[product_id]
        
        request.session.modified = True
        return redirect('cart:cart_detail')

def cart_clear(request):
    del request.session[settings.CART_ID]

cart/templates/cart/detail.html
{% extends 'base.html' %}
<br>
{% block title %}Shopping cart{% endblock title %}
<br>
{% block content  %}

<div class="card shadow-custom border-0 col-lg-10 mx-auto mb-3">
    <h3 class="py-2 font-weight-bold text-grey text-center">
      Your order:
    </h3>
    <div class="row justify-content-center py-2 text-center header-desc">
      <div class="col-lg-2 align-self-center">
        Product
      </div>
      <div class="col-lg-2 align-self-center">
        Description
      </div>
      <div class="col-lg-2 align-self-center">
        Availability
      </div>
      <div class="col-lg-1 align-self-center">
        Price
      </div>
      <div class="col-lg-2 align-self-center">
        Quantity
      </div>
      <div class="col-lg-3 align-self-center">
        Total price
      </div>
    </div>
    <hr class="mt-0">
    {% for item in cart %}
      {% with product=item.product %}
        <div class="row justify-content-center cart">
          <div class="cart-item col-4 col-lg-2">
            <a href="{{ product.get_absolute_url }}">
              <img src="{{ product.image.url }}" alt=""
                class="img-fluid rounded-0">
            </a>
          </div>
        <div class="cart-item product-name col-12
          col-lg-2 align-self-center text-center">
          {{ product.name }}
        </div>
         <div class="cart-item col-12 col-lg-2 align-self-center">
        {% if product.available %}
          <div class="text-green mb-0 text-center">
            Available
          </div>
        {% else %}
          <div class="text-danger mb-0 text-center">
            Currently unavailable
          </div>
        {% endif %}
        </div>
        <div class="cart-item col-12 col-sm-3
          col-lg-1 align-self-center text-center">
          <span>${{ product.price }}</span>
        </div>
        <div class="cart-item col-6 col-sm-5 col-lg-2 align-self-center">
          <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {% csrf_token %}
            <span class="input-group shopping-cart">
             {{item.update_quantity_form.quantity}}
              <input type="hidden" name="overwrite_qty" value="True">
              <div class="input-group-append">
                <button type="submit" class="btn text-white"
                  data-toggle="tooltip" data-placement="top"
                  title="Update">
                  <i class="fas fa-edit"></i>
                </button>
              </div>
            </span>
          </form>
        </div>
        <div class="cart-item col-12 col-sm-3
          col-lg-2 align-self-center text-right">
          <span>${{ item.total_price }}</span>
        </div>
        <div class="cart-item col-12 col-lg-1 text-right
          align-self-center">
          <form action="{% url 'cart:cart_remove' product.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn" data-toggle="tooltip"
              data-placement="top" title="Remove">
              <i class="fas fa-trash-alt"></i>
            </button>
           </form>
        </div>
      </div>
      {% endwith %}
    {% empty %}
    <div class="align-self-center">
      <span class="text-center font-weight-bold text-muted lead">
        Your shopping cart is empty.
      </span>
    </div>
    {% endfor %}
    <hr>
    <div class="total-price-cart">
      <h4 class="row justify-content-center">

        <div class="col-5 col-lg-9 text-right text-grey">
          Total price:
        </div>
        <div class="col-5 col-lg-2 text-right text-danger">
          ${{ cart_total_price|floatformat:2 }}
        </div>
        <div class="col-2 col-lg-1">
        </div>
      </h4>
    </div>
  </div>
  <hr>
  <div class="col-lg-10 mx-auto mb-5">
    <div class="row justify-content-end">
      {% if cart|length > 0 %}
      <div class="col-lg-6 px-0">
        <div class="btn-group d-flex">
          <a href="{% url 'listings:product_list' %}"
            class="btn btn-warning shadow-custom col">
            Back to shop
          </a>
          <a href="{% url 'orders:order_create' %}" class="btn btn-danger shadow-custom col">
            Checkout
          </a>
        </div>
      </div>
      {% else %}
      <div class="col-lg-3 px-0">
        <div class="btn-group d-flex">
          <a href="{% url 'listings:product_list'  %}" class="btn btn-warning shadow-custom col">Back to shop
          </a>
        </div>
      </div>
      {% endif %}
    </div>
  </div>

{% endblock content  %}