accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),

    #password change
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    #password reset
    path('password_reset/', auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/<uidb64>/<token>/',
    auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/',
    auth_views.PasswordResetCompleteView.as_view(),
    name='password_reset_complete'),

]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views

from django.contrib.admin.views.decorators import staff_member_required
from solarlynx.decorators import user_created_order

app_name='orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/pdf/', staff_member_required(views.invoice_pdf), name='invoice_pdf'),
    path('order/<int:order_id>/', user_created_order(views.order_detail), name='order_detail'),
    path('order/<int:order_id>/pdf/', user_created_order(views.invoice_pdf), name='customer_invoice_pdf'),

]

solarlynx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('listings.urls')),
 

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete = models.CASCADE
    )
    phone_number = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=250, blank=True)
    postal_code = models.CharField(max_length=20, blank=True)
    city = models.CharField(max_length=100, blank=True)
    country = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return f'{self.user.username} profile'

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
class LoginForm(forms.Form):
    email = forms.CharField(
        widget=forms.EmailInput(attrs={'class': 'form-control'
        })
    )
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))



class UserRegistrationForm(forms.ModelForm):
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password')

        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.EmailInput(attrs={'class':'form-control'}),
            'password':forms.PasswordInput(attrs={'class':'form-control'}),
        }

class UpdateUserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

        widgets = {
            'first_name': forms.TextInput(attrs={'class':'form-control'}
            ),
            'last_name': forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}
            )
        }
class UpdateProfileForm(forms.ModelForm):

    class Meta:
        model = Profile

        fields= ('phone_number', 'address', 'postal_code', 'city', 'country')

        widgets = {
            'phone_number': forms.TextInput(attrs={'class':'form-control'}
            ),

            'address': forms.TextInput(attrs={'class':'form-control'}
            ),

            'postal_code': forms.TextInput(attrs={'class':'form-control'}
            ),
            'city': forms.TextInput(attrs={'class':'form-control'}
            ),

            'country': forms.TextInput(attrs={'class':'form-control'}
            )
        }

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.models import User
from .models import Profile

from .forms import LoginForm, UserRegistrationForm, UpdateUserForm, UpdateProfileForm

from django.contrib.auth.decorators import login_required

@login_required
def profile(request):

    if request.method == 'POST':
        email = request.POST['email']
        user = None 

        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            pass
        
        if user is None or user.id == request.user.id:
            user_form = UpdateUserForm(
                instance=request.user,
                data = request.POST
            )
            profile_form = UpdateProfileForm(
                instance=request.user.profile,
                data = request.POST
            )

            if user_form.is_valid() and profile_form.is_valid():
                user_form.save()
                profile_form.save()

                messages.success(request, 'Profile was updated successfully')
        else:
            messages.error(request, 'User with given email already exists')

        return redirect('profile')
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)

    return render(request, 'accounts/profile.html', 
    {
        'user_form': user_form, 'profile_form': profile_form}
    )




        



# Create your views here.

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cf = form.cleaned_data
            user_record = None
            try:
                user_record = User.objects.get(email=cf['email'])
            except User.DoesNotExist:
                pass
            if user_record:
                user = authenticate(
                    request,
                    username= user_record,
                    password= cf['password'])

                if user is not None:
                    login(request, user)
                    return redirect('listings:product_list')
            messages.error(request, 'Incorrect email / password')
    else:
        form = LoginForm()
    
    return render(request, 'accounts/login.html', {'form': form})

def register(request):

    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            cf = user_form.cleaned_data

            email = cf['email']
            password = cf['password']
            password2 = cf['password2']

            if password == password2:

                if User.objects.filter(email=email).exists():
                    messages.error(request, 'User with given email already exists')

                    return render(request, 
                    'accounts/register.html',{'user_form':user_form}
                    )
            else:
                messages.error(request, 'Password don\'t match')
                return render(request, 
                    'accounts/register.html',{'user_form':user_form}
                    )
            # Create a new user object

            new_user = User.objects.create_user(
                first_name=cf['first_name'],
                last_name=cf['last_name'],
                username=email,
                email = email,
                password = password
            )

            # Create  the user profile

            Profile.objects.create(user=new_user)
            
            return render(request, 'accounts/register_done.html', {'new_user':new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'accounts/register.html',{'user_form':user_form})
            

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}Log in{% endblock %}
{% block content %}

{% if messages %}
   <div class="shadow-custom messages alert alert-danger
     col-lg-4 mx-auto text-center">
  {% for message in messages %}
        {% if message.tags == 'error' %}
            {{ message }}
             <a href="" class="close">x</a>
        {% endif %}
  {% endfor %}
  </div>
{% endif %}

<div class="card shadow-custom border-0 col-lg-4 mx-auto mb-3">
  <h3 class="py-2 font-weight-bold text-grey text-center">Log in</h3>
  <form action="" method="post">
     {% csrf_token %}
    <div class="input-field">
      {{ form.email }}
     <label for="email">Email</label>
    </div>
    <div class="input-field">
       {{ form.password }}
     <label for="password">Password</label>
    </div>
    <button class="btn btn-block btn-warning mb-3" type="submit">
    Log in
    </button>
  </form>
  <div class="text-center mb-2">
    <a href="{% url 'password_reset' %}"
      class="text-decoration-none">
      Forgot your password?
    </a>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block title %}Account{% endblock %}
{% block content %}
{% if messages %}
  {% for message in messages %}
    {% if message.tags == 'error' %}
    <div class="shadow-custom messages alert alert-danger text-center
      col-lg-7 mx-auto">
    {% else %}
    <div class="shadow-custom messages alert alert-success text-center
      col-lg-7 mx-auto">
    {% endif %}
      {{ message }}
      <a href="" class="close">x</a>
    </div>
  {% endfor %}
{% endif %}
  <div class="card shadow-custom border-0 col-lg-7 mx-auto mb-3">
    <h2 class="font-weight-bold text-grey mt-2">Profile</h2>
    <form action="" method="POST">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6">
          <div class="input-field">
            {{ user_form.first_name }}
            <label for="first_name">First name</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="input-field">
             {{ user_form.last_name }}
            <label for="last_name">Last name</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="input-field">
            {{ user_form.email }}
            <label for="email">Email</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="input-field">
            {{ profile_form.phone_number }}
            <label for="phone_number">Phone number</label>
          </div>
        </div>
      </div>
      <hr class="mt-0">

      <div class="row">
        <div class="col-md-6">
          <div class="input-field">
            {{ profile_form.address }}
            <label for="address">Address</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="input-field">
            {{ profile_form.postal_code }}
            <label for="postal_code">Postal code</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="input-field">
            {{ profile_form.city }}
            <label for="city">City</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="input-field">
            {{ profile_form.country }}
            <label for="country">Country</label>
          </div>
         </div>
      </div>
      <hr>
      <div class="row">
        <button type="submit" class="btn col" data-toggle="tooltip"
          data-placement="top"
          title="Fill in new details and click 'Update profile'">
          Update profile</button>
        <a class="btn col" href="{% url 'password_change' %}">
          Change password
        </a>
      </div>
      <hr>

      <h3 class="mb-3">Your orders:</h3>
       <table class="table">
  {% for order in request.user.orders.all %}
   <tr>
      <td>
        <a href="{{order.get_absolute_url}}" class="text-decoration-none">
          {{ order.id }}
        </a>
      </td>
      <td>{{ order.created|date }}</td>
      <td class="text-green">
        ${{ order.get_total_cost|floatformat:2 }}
      </td>
      <td>
        <a href="{% url 'orders:customer_invoice_pdf' order.id %}" class="text-decoration-none" target="_blank">
          <i class="far fa-file-pdf text-danger"></i>
          Invoice {{ order.id }}
        </a>
      </td>
      <td>{{ order.status }}</td>
    </tr>
    {% empty %}
    <tr>
      No orders yet
    </tr>
  {% endfor %}
</table>



    </form>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}
{% block content %}
{% if messages %}
    <div class="shadow-custom messages alert alert-danger col-lg-5 mx-auto text-center">
        {% for message in messages %}
            {{ message }}
            <a href="" class="close">x</a>
        {% endfor %}
    </div>
{% endif %}
<div class="card shadow-custom border-0 col-lg-5 mx-auto mb-3">
<h3 class="py-2 font-weight-bold text-grey text-center">Register</h3>
    <form action="" method="post">
        <div class="form-group">
           {% csrf_token %}
        <div class="input-field">
           {{ user_form.first_name }}
           <label for="first_name">First name</label>
        </div>
        <div class="input-field">
           {{ user_form.last_name }}
           <label for="last_name">Last name</label>
        </div>
        <div class="input-field">
           {{ user_form.email }}
           <label for="email">Email</label>
        </div>
        <div class="input-field">
           {{ user_form.password }}
           <label for="password">Password</label>
        </div>
        <div class="input-field">
           {{ user_form.password2 }}
           <label for="password2">Repeat password</label>
        </div>
        </div>
            <button class="btn btn-block btn-warning mb-3" type="submit">
                Register
            </button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/register_done.html
{% extends 'base.html' %}
{% block title %}Registration Complete{% endblock %}
{% block content %}
<div class="card shadow-custom border-0 col-lg-5 mx-auto mb-3 text-center">
<h3 class="py-2 font-weight-bold text-grey">
Welcome, {{ new_user.first_name }}
</h3>
<hr class="my-0">
<div class="py-2">
Your account was successfully created.
You can <a href="{% url 'login' %}">log in.</a>
</div>
</div>
{% endblock %}