cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

listings/urls.py
from django.urls import path 

from . import views

app_name = 'listings'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>', views.product_list, name='product_list_by_category'),
    path('<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),

]

solarlynx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('listings.urls')),
 

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"

        ordering = ('-name',)
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse(
            'listings:product_list_by_category', args=[self.slug]
            )

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    image = models.ImageField(upload_to="products/")
    description = models.TextField()
    shu = models.CharField(max_length=10)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ('shu',)

    def get_absolute_url(self):

        return reverse(
            'listings:product_detail', args=[self.category.slug, self.slug]
        )

    
    def get_average_review_scrore(self):
        average_score = 0.0
        if self.reviews.count() > 0:
            total_score = sum([review.rating for review in self.reviews.all()])
            average_score = total_score / self.reviews.count()
        return round(average_score, 1)

        
class Review(models.Model):

    product = models.ForeignKey(Product, related_name='reviews', on_delete=models.CASCADE)
    author = models.CharField(max_length=50)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    text = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    class Meta:

        ordering = ('-created',)
    

listings/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['text', 'rating']
        widgets = {
            'text': forms.Textarea(attrs={
                'class':'form-control shadow px-2',
                'row':6
            }
            ),
            'rating':forms.RadioSelect
        }

listings/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Category, Product, Review
from .forms import ReviewForm
from cart.forms import CartAddProductForm

# Create your views here.


def product_list(request, category_slug=None):
    categories = Category.objects.all()
    requested_category = None
    products = Product.objects.all()

    if category_slug:
        requested_category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=requested_category)

    return render(request, 'product/list.html', {'categories': categories,
    'requested_category':requested_category,
    'products': products})

def product_detail(request, category_slug, product_slug):

    category = get_object_or_404(Category, slug=category_slug)
    product = get_object_or_404(Product, 
    category_id=category.id, 
    slug=product_slug)

    if request.method == 'POST':
        Review_form = ReviewForm(request.POST)

        if Review_form.is_valid():
            cd = Review_form.cleaned_data
            author_name = 'Anonymous'
            if request.user.is_authenticated and request.user.first_name != '':
                author_name = request.user.first_name
            Review.objects.create(
                product = product,
                author = author_name,
                rating = cd['rating'],
                text = cd['text']
            )
        return redirect('listings:product_detail', category_slug=category_slug, product_slug=product_slug)
    else:
        review_form = ReviewForm()
        cart_product_form =CartAddProductForm()

    return render(request,
        'product/detail.html',
        {
            'product':product,
            'review_form':review_form,
            'cart_product_form':cart_product_form
            })

listings/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet"href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito&display=swap">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-danger fixed-top py-1"
    id="main-nav">
        <div class="container">
            <a href="{% url 'listings:product_list' %}" class="navbar-brand">
             <h3 class="font-weight-bold">solarlynx</h3>
            </a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url 'profile' %}" class="nav-link text-white">
                                <i class="fas fa-user"></i>{{request.user.email}}
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'logout' %}" class="nav-link text-white">
                                <i class="fas fa-sign-out-alt"></i>Log out
                            </a>
                        </li>
                        {% else %}

                        <li class="nav-item">
                            <a href="{% url 'login' %}" class="nav-link text-white">
                                <i class="fas fa-user-plus"></i>Log in
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'register' %}" class="nav-link text-white">
                                <i class="fas fa-user-plus"></i>Register
                            </a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <div class="dropdown-custom">
                            <a href="{% url 'cart:cart_detail' %}" class="nav-link text-white drop-btn">
                                <i class="fas fa-shopping-cart"></i>
                                $<span id="cart_total_price">{{cart_total_price|floatformat:2}}</span>
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container py-5">

    {% block content %}

    {% endblock content %}

    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
    integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>
    <script src=" {% static 'js/scripts.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js">
    </script>
</body>
</html>